[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
  -DUSER_SETUP_LOADED=1
  -include include/User_Setup.h
  -DLV_CONF_INCLUDE_SIMPLE
  -DLV_CONF_PATH=\"${PROJECT_DIR}/include/lv_conf.h\"
; Avoid DTR/RTS toggling resetting the board when opening the monitor (macOS flake).
monitor_rts = 0
monitor_dtr = 0
lib_deps =
  bogde/HX711
  bodmer/TFT_eSPI
  lvgl/lvgl
